# Generated by Django 6.0.4 on 2026-04-27 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Vehículo (Marca/Modelo)')),
                ('descripcion', models.TextField(verbose_name='¿Qué sucede?')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Dirección o Coordenadas')),
                ('tipo', models.CharField(choices=[('MEC', 'Mecánica General'), ('BAT', 'Batería / Eléctrico'), ('NEU', 'Neumáticos'), ('GRU', 'Remolque / Grúa')], default='MEC', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
