# Generated by Django 6.0.4 on 2026-04-27 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='¿Qué sucede?'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('MEC', 'Mecánica Ligera'), ('BAT', 'Batería / Arranque'), ('NEU', 'Neumáticos'), ('GRU', 'Grúa (Local)'), ('GRL', 'Grúa (Larga Distancia)')], default='MEC', max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ubicacion',
            field=models.CharField(max_length=255, verbose_name='Destino Final'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='vehiculo',
            field=models.CharField(max_length=100, verbose_name='Vehículo'),
        ),
    ]
