# Generated by Django 6.0.4 on 2026-04-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_solicitud_options_solicitud_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='latitud_coyote',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud_coyote',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
